name: ecommerce_application
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_ui_auth: ^1.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.2
  provider: ^6.0.5
  connectivity_plus: ^2.3.0
  auto_route: ^7.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/samples/restaurant.json
